version: '3'

services:
  app:
    build: .
    container_name: cod3r_app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://postgres:5432 -timeout 40s ./.docker/app/entrypoint.sh
    environment:
      - DB_HOST=postgres
      - DB_DATABASE=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    restart: always
    ports:
      - "3865:3000"
    volumes:
      - .:/usr/src
    networks:
      - app-network
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:10
    container_name: cod3r_postgres
    restart: always
    ports:
      - "5436:5432"
    volumes:
      - "./.docker/postgresql/postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: cod3r_mongo
    restart: always
    tty: true
    ports:
      - 27019:27017
    volumes:
      - ./.docker/mongo/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
